COURSES = [
    {
        "name": "Course 1: Exploring Microsoft Azure",
        "url": "https://cs.edukamu.fi/exploring-azure",
        "sections": [
            "https://cs.edukamu.fi/exploring-azure/1/basics-of-azure",
            "https://cs.edukamu.fi/exploring-azure/1/physical-infrastructure",
            "https://cs.edukamu.fi/exploring-azure/1/management-infrastructure",
            "https://cs.edukamu.fi/exploring-azure/1/computing-service",
            "https://cs.edukamu.fi/exploring-azure/1/virtual-networking",
            "https://cs.edukamu.fi/exploring-azure/2/azure-storage",
            "https://cs.edukamu.fi/exploring-azure/2/storage-services",
            "https://cs.edukamu.fi/exploring-azure/2/data-migration",
            "https://cs.edukamu.fi/exploring-azure/2/authentication-and-authorization",
            "https://cs.edukamu.fi/exploring-azure/2/conditional-access",
            "https://cs.edukamu.fi/exploring-azure/3/project-management-in-azure",
            "https://cs.edukamu.fi/exploring-azure/3/managing-with-azure-arc",
            "https://cs.edukamu.fi/exploring-azure/3/governance-and-compliance",
            "https://cs.edukamu.fi/exploring-azure/3/cost-management",
            "https://cs.edukamu.fi/exploring-azure/3/summary",
        ],
    },
    {
        "name": "Course 2: Exploring Artificial Intelligence",
        "url": "https://cs.edukamu.fi/exploring-ai",
        "sections": [
            "https://cs.edukamu.fi/exploring-ai/1/fundamental-concepts-of-ai",
            "https://cs.edukamu.fi/exploring-ai/1/introduction-to-machine-learning",
            "https://cs.edukamu.fi/exploring-ai/1/supervised-learning",
            "https://cs.edukamu.fi/exploring-ai/1/unsupervised-learning",
            "https://cs.edukamu.fi/exploring-ai/1/azure-and-ai",
            "https://cs.edukamu.fi/exploring-ai/2/fundamental-concepts-of-computer-vision",
            "https://cs.edukamu.fi/exploring-ai/2/ai-and-facial-recognition",
            "https://cs.edukamu.fi/exploring-ai/2/recognizing-characters-with-ai",
            "https://cs.edukamu.fi/exploring-ai/3/fundamental-concepts-of-nlp",
            "https://cs.edukamu.fi/exploring-ai/3/question-answering",
            "https://cs.edukamu.fi/exploring-ai/3/conversational-language-understanding",
            "https://cs.edukamu.fi/exploring-ai/3/azure-and-ai-speech",
            "https://cs.edukamu.fi/exploring-ai/4/fundamentals-of-generative-ai",
            "https://cs.edukamu.fi/exploring-ai/4/azure-openai-services",
            "https://cs.edukamu.fi/exploring-ai/4/ai-and-copilots",
            "https://cs.edukamu.fi/exploring-ai/4/responsibility-and-ethics",
            "https://cs.edukamu.fi/exploring-ai/5/fundamental-concepts-of-di",
            "https://cs.edukamu.fi/exploring-ai/5/azure-and-cognitive-search",
            "https://cs.edukamu.fi/exploring-ai/5/enriched-data-and-query-design",
            "https://cs.edukamu.fi/exploring-ai/5/azure-ai-search",
            "https://cs.edukamu.fi/exploring-ai/5/summary",
        ],
    },
    {
        "name": "Course 3: Exploring Data and Analytics",
        "url": "https://cs.edukamu.fi/exploring-data-and-analytics",
        "sections": [
            "https://cs.edukamu.fi/exploring-data-and-analytics/1/identifying-data",
            "https://cs.edukamu.fi/exploring-data-and-analytics/1/databases-and-processing",
            "https://cs.edukamu.fi/exploring-data-and-analytics/1/data-roles-and-services",
            "https://cs.edukamu.fi/exploring-data-and-analytics/2/exploring-relational-data",
            "https://cs.edukamu.fi/exploring-data-and-analytics/2/relational-databases-in-azure",
            "https://cs.edukamu.fi/exploring-data-and-analytics/2/adopting-cloud-services",
            "https://cs.edukamu.fi/exploring-data-and-analytics/2/exploring-non-relational-data",
            "https://cs.edukamu.fi/exploring-data-and-analytics/2/fundamentals-of-azure-cosmos-db",
            "https://cs.edukamu.fi/exploring-data-and-analytics/3/large-scale-analytics",
            "https://cs.edukamu.fi/exploring-data-and-analytics/3/real-time-analytics",
            "https://cs.edukamu.fi/exploring-data-and-analytics/3/data-visualization",
            "https://cs.edukamu.fi/exploring-data-and-analytics/3/summary",
        ],
    },
    {
        "name": "Course 4: Accelerating Development Workflow",
        "url": "https://cs.edukamu.fi/accelerating-development-workflow",
        "sections": [
            "https://cs.edukamu.fi/accelerating-development-workflow/1/introduction-to-github",
            "https://cs.edukamu.fi/accelerating-development-workflow/1/collaboration-in-github",
            "https://cs.edukamu.fi/accelerating-development-workflow/1/administration-in-github",
            "https://cs.edukamu.fi/accelerating-development-workflow/1/managing-permissions",
            "https://cs.edukamu.fi/accelerating-development-workflow/2/introduction-to-github-copilot",
            "https://cs.edukamu.fi/accelerating-development-workflow/2/prompt-engineering",
            "https://cs.edukamu.fi/accelerating-development-workflow/2/github-copilot-for-business",
            "https://cs.edukamu.fi/accelerating-development-workflow/3/github-copilot-and-javascript",
            "https://cs.edukamu.fi/accelerating-development-workflow/3/github-copilot-and-python",
            "https://cs.edukamu.fi/accelerating-development-workflow/3/automating-workflows-with-github-actions",
            "https://cs.edukamu.fi/accelerating-development-workflow/3/summary",
        ],
    },
    {
        "name": "Course 5: Getting Started with Cloud Native Data Storage",
        "url": "https://cs.edukamu.fi/cloud-native-data-storage",
        "sections": [
            "https://cs.edukamu.fi/cloud-native-data-storage/1/empowering-global-applications",
            "https://cs.edukamu.fi/cloud-native-data-storage/1/introduction-to-azure-cosmos-db",
            "https://cs.edukamu.fi/cloud-native-data-storage/1/exploring-global-databases",
            "https://cs.edukamu.fi/cloud-native-data-storage/1/components-of-cosmos-db-for-nosql",
            "https://cs.edukamu.fi/cloud-native-data-storage/2/azure-cosmos-db-in-action",
            "https://cs.edukamu.fi/cloud-native-data-storage/2/planning-nosql-solutions",
            "https://cs.edukamu.fi/cloud-native-data-storage/2/implementing-nosql-solutions",
            "https://cs.edukamu.fi/cloud-native-data-storage/2/migrating-data",
            "https://cs.edukamu.fi/cloud-native-data-storage/3/connecting-to-a-nosql-database",
            "https://cs.edukamu.fi/cloud-native-data-storage/3/configuring-the-sdk",
            "https://cs.edukamu.fi/cloud-native-data-storage/3/advanced-capabilities-of-azure-cosmos-db",
            "https://cs.edukamu.fi/cloud-native-data-storage/3/summary",
        ],
    },
    {
        "name": "Course 6: Getting Started with Azure Development",
        "url": "https://cs.edukamu.fi/azure-development",
        "sections": [
            "https://cs.edukamu.fi/azure-development/1/introduction-to-azure-ai-development",
            "https://cs.edukamu.fi/azure-development/1/getting-started-with-azure-app-service",
            "https://cs.edukamu.fi/azure-development/1/configuring-web-apps",
            "https://cs.edukamu.fi/azure-development/1/discovering-azure-functions",
            "https://cs.edukamu.fi/azure-development/2/handling-unstructured-data",
            "https://cs.edukamu.fi/azure-development/2/ensuring-data-availability",
            "https://cs.edukamu.fi/azure-development/2/containerized-solutions",
            "https://cs.edukamu.fi/azure-development/2/comparing-container-services",
            "https://cs.edukamu.fi/azure-development/2/implementing-container-apps",
            "https://cs.edukamu.fi/azure-development/3/enhancing-security",
            "https://cs.edukamu.fi/azure-development/3/securing-app-configurations",
            "https://cs.edukamu.fi/azure-development/3/exploring-api-management",
            "https://cs.edukamu.fi/azure-development/3/advanced-capabilities",
            "https://cs.edukamu.fi/azure-development/3/summary",
        ],
    },
    {
        "name": "Course 7: Getting Started with AI Development",
        "url": "https://cs.edukamu.fi/ai-development",
        "sections": [
            "https://cs.edukamu.fi/ai-development/1/getting-started-with-azure-ai-services",
            "https://cs.edukamu.fi/ai-development/1/enabling-azure-ai-services",
            "https://cs.edukamu.fi/ai-development/1/deploying-azure-ai-containers",
            "https://cs.edukamu.fi/ai-development/1/getting-started-with-azure-ai-language",
            "https://cs.edukamu.fi/ai-development/2/building-natural-language-solutions",
            "https://cs.edukamu.fi/ai-development/2/conversational-language-understanding",
            "https://cs.edukamu.fi/ai-development/2/capabilities-of-clu",
            "https://cs.edukamu.fi/ai-development/3/retrieving-information-with-azure-ai-search",
            "https://cs.edukamu.fi/ai-development/3/rag-capabilities-in-microsoft-azure",
            "https://cs.edukamu.fi/ai-development/3/introduction-to-building-natural-language-solutions",
            "https://cs.edukamu.fi/ai-development/4/getting-started-with-azure-openai",
            "https://cs.edukamu.fi/ai-development/4/fine-tuning-effective-prompts",
            "https://cs.edukamu.fi/ai-development/4/generating-code-with-ai",
            "https://cs.edukamu.fi/ai-development/4/responsible-generative-ai",
            "https://cs.edukamu.fi/ai-development/4/summary",
        ],
    },
]
